### ISSUE TITLE
References to deleted files

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1125] opened 2021-09-03 13:25 UTC
# Bug Report

## Description

When indexing, there are some files that are getting referenced that have been deleted:

```
ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find FileResource with 'id'=15422
```

## To Reproduce
1. Find the related work that has that id
2. index the work

## Todo

Remove the references? Why is this happening in the first place?

**Comment by srerickson** [comment] 2022-01-06 18:49
things to look at:
- latency in job queue (file deleted while waiting)
- reindexing

**Comment by awead** [comment] 2022-01-06 20:51
There are several of these in QA and not just files: https://scholarsphere-qa.dsrd.libraries.psu.edu/admin/sidekiq/morgue

I think the issue is that if a work version or file is deleted and then its updated work is indexed, the job executes after the object is deleted. The easiest way to solve this might be to just rescue these errors. If we try to index an item that doesn't exist in the database, there's not much we can do about it.

**Comment by banukutlu** [comment] 2022-01-26 16:48
Since there is no UI to delete a FileResource, we think this error could only occur when a FileResource is directly deleted from the database by a developer. Since it is a low priority and unlikely to happen with regular flow of the application, we will close this for now and keep an eye for it.

**Comment by whereismyjetpack** [comment] 2022-01-27 13:23
Well, that was kind of short lived. This morning we got another file not found message. It seems a user was able to step through the process, but the workversion is not there. I'm doing some forensics now, trying to understand what the user did.

**Comment by whereismyjetpack** [comment] 2022-01-27 13:46
To reproduce: 

If i user chooses the "x" button in the uppy interface, it sends a `DELETE` but the indexing job with that id still gets queued up.  I'm still investigating but putting this here so I don't forget


^this might not be 100% accurate. still investigating

**Comment by whereismyjetpack** [comment] 2022-01-27 13:49
related logs
![Screen Shot 2022-01-27 at 8 47 19 AM](https://user-images.githubusercontent.com/3694886/151371583-87f058e2-70a1-43df-9097-e34ee14da20d.png)

![Screen Shot 2022-01-27 at 8 48 55 AM](https://user-images.githubusercontent.com/3694886/151371658-d1edfb89-bd16-4860-bbe0-6b168e4c46b4.png)

**Comment by srerickson** [comment] 2022-01-27 13:50
This may be related to #1127

**Comment by whereismyjetpack** [comment] 2022-01-27 21:15
When we see these in the Dead Set queue, they are probably created due to a race condition For example:

User creates a new version, adds a collaborator, then updates some metadata (this queues up n number of jobs)
User immediately deletes the new version they created (tracing the logs, this is what appears to have happened this morning, a job got queued up within seconds of deleting the workversion)

We can't just rescue the error though, because we see the same error when creating a new work, however sidekiq's retry logic will index the changes on the second try 

https://user-images.githubusercontent.com/3694886/151444723-679d775d-95aa-405f-a437-e6ba6096321b.mov


Attached is a screen recording demonstrating the second scenario

**Comment by ajkiessl** [comment] 2024-01-23 18:29
Ah, yeah this is a race condition.  When creating a new WorkVersion, FileResource, or Collection, if you click through the first step (or click through the file upload step) it looks like the database transactions that store the new records do not complete before the indexing jobs complete.  Therefore, the indexing jobs cannot find the records to index.  I don't think this has anything to do with the user deleting anything.  

The solution to this may just be to move the invocation of the indexing jobs to after the db transactions complete.  I'll have to figure out where this is in the code.

This would explain #1440 as well

**Closed as completed** 2024-01-25 14:16 UTC
Labels: bug

**Comment by ajkiessl** [comment] 2024-01-25 16:59
Tested in QA and looks to be working.
